[phases.setup]
nixPkgs = [
  "nodejs_18",
  "chromium",
  "wget",
  "curl",
  "git",
  "bash",
  "glibc",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "gdk-pixbuf",
  "gtk3",
  "pango",
  "cairo",
  "freetype",
  "fontconfig",
  "alsa-lib",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXrender",
  "xorg.libXtst",
  "mesa",
  "libdrm",
  "libgbm",
  "libxkbcommon"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
