[phases.setup]
nixPkgs = [
  "nodejs_18",
  "google-chrome",
  "wget",
  "curl",
  "git",
  "bash",
  "glibc",
  "nss",
  "nspr",
  "atk",
  "atkmm",
  "cups",
  "dbus",
  "expat",
  "gdk-pixbuf",
  "gtk3",
  "pango",
  "cairo",
  "freetype",
  "fontconfig",
  "alsa-lib",
  "libX11",
  "libXcomposite",
  "libXcursor",
  "libXdamage",
  "libXext",
  "libXi",
  "libXrandr",
  "libXrender",
  "libXtst",
  "libxkbcommon",
  "mesa",
  "libdrm",
  "libgbm"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

